import { TimelineUniverse } from "@/types/timeline";

const BASE_X = 100;
const STEP_X = 230;
const MAIN_Y = 300;
const ELSEWORLDS_Y = -140;
const CHAPTER1_Y = 640;

export const dcuTimeline: TimelineUniverse = {
  id: "dcu",
  name: "DC Cinematic Universe",
  shortName: "DC Universe",
  description:
    "Chronological saga of the DC Multiverse, from the Snyderverse era through the newly rising DCU Chapter 1: Gods and Monsters.",
  accentColor: "#2563EB",
  category: "film_tv",
  defaultFilterId: "all",
  filters: [
    {
      id: "all",
      label: "All DC Eras",
      description: "Snyderverse, Elseworlds, and DCU Gods & Monsters",
    },
    {
      id: "sacred",
      label: "Mainline DCEU",
      description: "Core cinematic timeline",
    },
    {
      id: "anchors",
      label: "Justice League & Key Events",
      description: "Anchor milestone events",
    },
  ],
  nodes: [
    {
      id: "dc-wonder-woman",
      type: "mediaNode",
      position: { x: BASE_X, y: MAIN_Y },
      data: {
        id: "dc-wonder-woman",
        tmdbId: 297762,
        mediaType: "movie",
        title: "Wonder Woman",
        releaseYear: "2017",
        chronologicalYear: "1918",
        posterPath: "/v4ncgZjG2Zu8ZW5al1vIZTsSjqX.jpg",
        rating: 7.2,
        phase: "DCEU Era",
        canonType: "sacred",
        branchName: "World War I",
      },
    },
    {
      id: "dc-ww84",
      type: "mediaNode",
      position: { x: BASE_X + STEP_X, y: MAIN_Y },
      data: {
        id: "dc-ww84",
        tmdbId: 464052,
        mediaType: "movie",
        title: "Wonder Woman 1984",
        releaseYear: "2020",
        chronologicalYear: "1984",
        posterPath: "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
        rating: 6.4,
        phase: "DCEU Era",
        canonType: "sacred",
        branchName: "Cold War Era",
      },
    },
    {
      id: "dc-man-of-steel",
      type: "mediaNode",
      position: { x: BASE_X + STEP_X * 2, y: MAIN_Y },
      data: {
        id: "dc-man-of-steel",
        tmdbId: 49521,
        mediaType: "movie",
        title: "Man of Steel",
        releaseYear: "2013",
        chronologicalYear: "2013",
        posterPath: "/8GFtkImmK0K1VaUChR0n9O61CFU.jpg",
        rating: 6.6,
        phase: "DCEU Era",
        canonType: "sacred",
        branchName: "Metropolis First Contact",
        isAnchor: true,
      },
    },
    {
      id: "dc-bvs",
      type: "mediaNode",
      position: { x: BASE_X + STEP_X * 3, y: MAIN_Y },
      data: {
        id: "dc-bvs",
        tmdbId: 209112,
        mediaType: "movie",
        title: "Batman v Superman: Dawn of Justice",
        releaseYear: "2016",
        chronologicalYear: "2015",
        posterPath: "/5UsK3grJvtQrtzEgqNlDljJW96w.jpg",
        rating: 6.0,
        phase: "DCEU Era",
        canonType: "sacred",
        branchName: "Dawn of Justice",
        isAnchor: true,
      },
    },
    {
      id: "dc-the-batman",
      type: "mediaNode",
      position: { x: BASE_X + STEP_X * 3, y: ELSEWORLDS_Y },
      data: {
        id: "dc-the-batman",
        tmdbId: 414906,
        mediaType: "movie",
        title: "The Batman",
        releaseYear: "2022",
        chronologicalYear: "Year Two",
        posterPath: "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
        rating: 7.7,
        phase: "Elseworlds",
        canonType: "multiverse",
        branchName: "The Batman Epic Crime Saga",
      },
    },
    {
      id: "dc-zsjl",
      type: "mediaNode",
      position: { x: BASE_X + STEP_X * 4, y: MAIN_Y },
      data: {
        id: "dc-zsjl",
        tmdbId: 791373,
        mediaType: "movie",
        title: "Zack Snyder's Justice League",
        releaseYear: "2021",
        chronologicalYear: "2017",
        posterPath: "/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg",
        rating: 8.1,
        phase: "DCEU Era",
        canonType: "sacred",
        branchName: "Unity Defense",
        isAnchor: true,
      },
    },
    {
      id: "dc-the-flash",
      type: "mediaNode",
      position: { x: BASE_X + STEP_X * 5, y: MAIN_Y },
      data: {
        id: "dc-the-flash",
        tmdbId: 298618,
        mediaType: "movie",
        title: "The Flash",
        releaseYear: "2023",
        chronologicalYear: "2023",
        posterPath: "/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
        rating: 6.7,
        phase: "Multiverse Reset",
        canonType: "multiverse",
        branchName: "Flashpoint Chronology Reset",
        isAnchor: true,
      },
    },
    {
      id: "dc-superman-2025",
      type: "mediaNode",
      position: { x: BASE_X + STEP_X * 6, y: CHAPTER1_Y },
      data: {
        id: "dc-superman-2025",
        tmdbId: 1061474,
        mediaType: "movie",
        title: "Superman",
        releaseYear: "2025",
        chronologicalYear: "2025",
        posterPath: "/ldyfo0BKmz5rWtJJKCvwaNS4cJT.jpg",
        rating: 7.5,
        phase: "DCU Chapter 1",
        canonType: "canon",
        branchName: "Gods and Monsters",
        isAnchor: true,
      },
    },
  ],
  edges: [
    { id: "e-dc-1", source: "dc-wonder-woman", target: "dc-ww84" },
    { id: "e-dc-2", source: "dc-ww84", target: "dc-man-of-steel" },
    { id: "e-dc-3", source: "dc-man-of-steel", target: "dc-bvs" },
    {
      id: "e-dc-4",
      source: "dc-man-of-steel",
      target: "dc-the-batman",
      sourceHandle: "top",
      targetHandle: "target-bottom",
      branchVariant: "multiverse",
      label: "ELSEWORLDS",
    },
    { id: "e-dc-5", source: "dc-bvs", target: "dc-zsjl" },
    { id: "e-dc-6", source: "dc-zsjl", target: "dc-the-flash" },
    {
      id: "e-dc-7",
      source: "dc-the-flash",
      target: "dc-superman-2025",
      sourceHandle: "bottom",
      targetHandle: "target-top",
      branchVariant: "secondary",
      label: "DCU REBIRTH",
    },
  ],
};
