import { TimelineUniverse } from "@/types/timeline";

const BASE_X = 100;
const STEP_X = 230;
const MAIN_Y = 300;
const PREQUEL_Y = -140;
const HOLLOW_Y = 640;

export const monsterverseTimeline: TimelineUniverse = {
  id: "monsterverse",
  name: "Godzilla & Kong: MonsterVerse",
  shortName: "MonsterVerse",
  description:
    "Follow the emergence of Titans, Monarch discoveries, and the battle for Hollow Earth in chronological MonsterVerse order.",
  accentColor: "#10B981",
  category: "scifi",
  defaultFilterId: "all",
  filters: [
    {
      id: "all",
      label: "All MonsterVerse",
      description: "Full chronological timeline of Titans and Monarch",
    },
    {
      id: "sacred",
      label: "Mainline Movies",
      description: "Godzilla and Kong major blockbuster releases",
    },
  ],
  nodes: [
    {
      id: "mv-kong-skull-island",
      type: "mediaNode",
      position: { x: BASE_X, y: MAIN_Y },
      data: {
        id: "mv-kong-skull-island",
        tmdbId: 293167,
        mediaType: "movie",
        title: "Kong: Skull Island",
        releaseYear: "2017",
        chronologicalYear: "1973",
        posterPath: "/r2517Vz9EhDhj88qwbDVj8DCRZN.jpg",
        rating: 6.6,
        phase: "Phase 1",
        canonType: "sacred",
        branchName: "Titans Awakening",
        isAnchor: true,
      },
    },
    {
      id: "mv-skull-island-series",
      type: "mediaNode",
      position: { x: BASE_X + STEP_X, y: PREQUEL_Y },
      data: {
        id: "mv-skull-island-series",
        tmdbId: 117678,
        mediaType: "tv",
        title: "Skull Island",
        releaseYear: "2023",
        chronologicalYear: "1990s",
        posterPath: "/8XApFlqookjHKWuScJgUoWnpFt8.jpg",
        rating: 7.0,
        phase: "Animation",
        canonType: "spinoff",
        branchName: "Skull Island Lore",
      },
    },
    {
      id: "mv-godzilla-2014",
      type: "mediaNode",
      position: { x: BASE_X + STEP_X * 2, y: MAIN_Y },
      data: {
        id: "mv-godzilla-2014",
        tmdbId: 124905,
        mediaType: "movie",
        title: "Godzilla",
        releaseYear: "2014",
        chronologicalYear: "2014",
        posterPath: "/tphkjmQq8WebuVwNXelmjLUXuPJ.jpg",
        rating: 6.3,
        phase: "Phase 1",
        canonType: "sacred",
        branchName: "San Francisco Emergence",
        isAnchor: true,
      },
    },
    {
      id: "mv-monarch-legacy",
      type: "mediaNode",
      position: { x: BASE_X + STEP_X * 3, y: HOLLOW_Y },
      data: {
        id: "mv-monarch-legacy",
        tmdbId: 202411,
        mediaType: "tv",
        title: "Monarch: Legacy of Monsters",
        releaseYear: "2023",
        chronologicalYear: "1950s / 2015",
        posterPath: "/7LBbaEaLSbqdviBYaSS1rRPMnrs.jpg",
        rating: 7.7,
        phase: "Series",
        canonType: "spinoff",
        branchName: "Monarch Secrets",
      },
    },
    {
      id: "mv-godzilla-kotm",
      type: "mediaNode",
      position: { x: BASE_X + STEP_X * 4, y: MAIN_Y },
      data: {
        id: "mv-godzilla-kotm",
        tmdbId: 373571,
        mediaType: "movie",
        title: "Godzilla: King of the Monsters",
        releaseYear: "2019",
        chronologicalYear: "2019",
        posterPath: "/mzOHg7Q5q9yUmY0b9Esu8Qe6Nnm.jpg",
        rating: 6.7,
        phase: "Phase 2",
        canonType: "sacred",
        branchName: "Alpha Titan War",
        isAnchor: true,
      },
    },
    {
      id: "mv-godzilla-vs-kong",
      type: "mediaNode",
      position: { x: BASE_X + STEP_X * 5, y: MAIN_Y },
      data: {
        id: "mv-godzilla-vs-kong",
        tmdbId: 399566,
        mediaType: "movie",
        title: "Godzilla vs. Kong",
        releaseYear: "2021",
        chronologicalYear: "2024",
        posterPath: "/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg",
        rating: 7.5,
        phase: "Phase 2",
        canonType: "sacred",
        branchName: "Hollow Earth Clash",
        isAnchor: true,
      },
    },
    {
      id: "mv-godzilla-x-kong",
      type: "mediaNode",
      position: { x: BASE_X + STEP_X * 6, y: MAIN_Y },
      data: {
        id: "mv-godzilla-x-kong",
        tmdbId: 823464,
        mediaType: "movie",
        title: "Godzilla x Kong: The New Empire",
        releaseYear: "2024",
        chronologicalYear: "2027",
        posterPath: "/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg",
        rating: 7.0,
        phase: "Phase 3",
        canonType: "sacred",
        branchName: "The New Empire",
        isAnchor: true,
      },
    },
  ],
  edges: [
    { id: "e-mv-1", source: "mv-kong-skull-island", target: "mv-godzilla-2014" },
    {
      id: "e-mv-2",
      source: "mv-kong-skull-island",
      target: "mv-skull-island-series",
      sourceHandle: "top",
      targetHandle: "target-bottom",
      branchVariant: "secondary",
    },
    {
      id: "e-mv-3",
      source: "mv-godzilla-2014",
      target: "mv-monarch-legacy",
      sourceHandle: "bottom",
      targetHandle: "target-top",
      branchVariant: "secondary",
    },
    { id: "e-mv-4", source: "mv-godzilla-2014", target: "mv-godzilla-kotm" },
    { id: "e-mv-5", source: "mv-godzilla-kotm", target: "mv-godzilla-vs-kong" },
    { id: "e-mv-6", source: "mv-godzilla-vs-kong", target: "mv-godzilla-x-kong" },
  ],
};
