export interface DiagramNode {
  id: string;
  title: string;
  mediaType: "movie" | "tv";
  mediaId: number;
  releaseYear: number;
  inUniverseTime: string;
  customPosterPath?: string;
  overview?: string;
  slug?: string;
  canon?: "canon" | "legends";
  markerType?: "split" | "merge" | null;
  // Zoomed In Coordinates (Canvas width: 5152px, height: 612px)
  zoomedIn: {
    left: number;
    top: number;
    width: number;
  };
  // Zoomed Out Coordinates (Canvas width: 2108px, height: 612px)
  zoomedOut: {
    left: number;
    top: number;
    width: number;
    isMini: boolean;
  };
}

export const STAR_WARS_DIAGRAM_NODES: DiagramNode[] = [
  {
    id: "tv-202998-star-wars-young-jedi-adventures",
    title: "Star Wars: Young Jedi Adventures",
    mediaType: "tv",
    mediaId: 202998,
    releaseYear: 2024,
    inUniverseTime: "233 to 232 BBY, the High Republic",
    customPosterPath: "/bC2Mix1WPUiY6pldh77oiFl1MvI.jpg",
    slug: "tv/202998-star-wars-young-jedi-adventures",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 70,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 55,
      top: 280.5,
      width: 34,
      isMini: true,
    },
  },
  {
    id: "tv-114479-the-acolyte",
    title: "The Acolyte",
    mediaType: "tv",
    mediaId: 114479,
    releaseYear: 2024,
    inUniverseTime: "132 BBY",
    customPosterPath: "/mztdt3y6GBsJR69zHtszFezTCLT.jpg",
    slug: "tv/114479-the-acolyte",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 228,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 87,
      top: 280.5,
      width: 34,
      isMini: true,
    },
  },
  {
    id: "movie-1893-star-wars-episode-i-the-phantom-menace",
    title: "Star Wars: Episode I - The Phantom Menace",
    mediaType: "movie",
    mediaId: 1893,
    releaseYear: 2024,
    inUniverseTime: "32 BBY",
    customPosterPath: "/6wkfovpn7Eq8dYNKaG5PY3q2oq6.jpg",
    slug: "movie/1893-star-wars-episode-i-the-phantom-menace",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 386,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 125,
      top: 246,
      width: 98,
      isMini: false,
    },
  },
  {
    id: "movie-1894-star-wars-episode-ii-attack-of-the-clones",
    title: "Star Wars: Episode II - Attack of the Clones",
    mediaType: "movie",
    mediaId: 1894,
    releaseYear: 2024,
    inUniverseTime: "22 BBY",
    customPosterPath: "/oZNPzxqM2s5DyVWab09NTQScDQt.jpg",
    slug: "movie/1894-star-wars-episode-ii-attack-of-the-clones",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 544,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 233,
      top: 246,
      width: 98,
      isMini: false,
    },
  },
  {
    id: "movie-12180-star-wars-the-clone-wars",
    title: "Star Wars: The Clone Wars",
    mediaType: "movie",
    mediaId: 12180,
    releaseYear: 2024,
    inUniverseTime: "22 BBY",
    customPosterPath: "/iJQfixW818LUdSXlCDL3JZm0S0g.jpg",
    slug: "movie/12180-star-wars-the-clone-wars",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 702,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 335,
      top: 280.5,
      width: 34,
      isMini: true,
    },
  },
  {
    id: "tv-4194-star-wars-the-clone-wars",
    title: "Star Wars: The Clone Wars",
    mediaType: "tv",
    mediaId: 4194,
    releaseYear: 2024,
    inUniverseTime: "22 to 19 BBY",
    customPosterPath: "/e1nWfnnCVqxS2LeTO3dwGyAsG2V.jpg",
    slug: "tv/4194-star-wars-the-clone-wars",
    canon: "canon",
    markerType: "split",
    zoomedIn: {
      left: 860,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 373,
      top: 246,
      width: 98,
      isMini: false,
    },
  },
  {
    id: "tv-203085-star-wars-tales-of-the-jedi",
    title: "Star Wars: Tales of the Jedi",
    mediaType: "tv",
    mediaId: 203085,
    releaseYear: 2024,
    inUniverseTime: "Six stories, the 60s BBY to 18 BBY",
    customPosterPath: "/k3nWQb0E8mLSR8acSkJP78VRVMv.jpg",
    slug: "tv/203085-star-wars-tales-of-the-jedi",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 1018,
      top: 40,
      width: 130,
    },
    zoomedOut: {
      left: 475,
      top: 68.5,
      width: 34,
      isMini: true,
    },
  },
  {
    id: "movie-1895-star-wars-episode-iii-revenge-of-the-sith",
    title: "Star Wars: Episode III - Revenge of the Sith",
    mediaType: "movie",
    mediaId: 1895,
    releaseYear: 2024,
    inUniverseTime: "19 BBY",
    customPosterPath: "/xfSAoBEm9MNBjmlNcDYLvLSMlnq.jpg",
    slug: "movie/1895-star-wars-episode-iii-revenge-of-the-sith",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 1176,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 513,
      top: 246,
      width: 98,
      isMini: false,
    },
  },
  {
    id: "tv-251091-star-wars-tales-of-the-empire",
    title: "Star Wars: Tales of the Empire",
    mediaType: "tv",
    mediaId: 251091,
    releaseYear: 2024,
    inUniverseTime: "Six stories, 20 BBY to 9 ABY",
    customPosterPath: "/qA28nLteurVboSSzltuyYt1lvlC.jpg",
    slug: "tv/251091-star-wars-tales-of-the-empire",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 1334,
      top: 40,
      width: 130,
    },
    zoomedOut: {
      left: 615,
      top: 68.5,
      width: 34,
      isMini: true,
    },
  },
  {
    id: "tv-288055-star-wars-tales-of-the-underworld",
    title: "Star Wars: Tales of the Underworld",
    mediaType: "tv",
    mediaId: 288055,
    releaseYear: 2024,
    inUniverseTime: "Six stories, the 50s BBY to the early Empire",
    customPosterPath: "/qv1hagzp08cDJF6C04LyJVhcI1x.jpg",
    slug: "tv/288055-star-wars-tales-of-the-underworld",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 1492,
      top: 40,
      width: 130,
    },
    zoomedOut: {
      left: 647,
      top: 68.5,
      width: 34,
      isMini: true,
    },
  },
  {
    id: "tv-105971-star-wars-the-bad-batch",
    title: "Star Wars: The Bad Batch",
    mediaType: "tv",
    mediaId: 105971,
    releaseYear: 2024,
    inUniverseTime: "19 BBY to 18 BBY",
    customPosterPath: "/5mHus672nuinyaE0FtqvD0AddcY.jpg",
    slug: "tv/105971-star-wars-the-bad-batch",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 1650,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 679,
      top: 280.5,
      width: 34,
      isMini: true,
    },
  },
  {
    id: "tv-289219-star-wars-maul-shadow-lord",
    title: "Star Wars: Maul - Shadow Lord",
    mediaType: "tv",
    mediaId: 289219,
    releaseYear: 2024,
    inUniverseTime: "17 BBY or so",
    customPosterPath: "/fTfLd3s9yBNOzbFHD2aXvwEs93H.jpg",
    slug: "tv/289219-star-wars-maul-shadow-lord",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 1808,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 711,
      top: 280.5,
      width: 34,
      isMini: true,
    },
  },
  {
    id: "movie-348350-solo-a-star-wars-story",
    title: "Solo: A Star Wars Story",
    mediaType: "movie",
    mediaId: 348350,
    releaseYear: 2024,
    inUniverseTime: "13 BBY to 10 BBY",
    customPosterPath: "/4oD6VEccFkorEBTEDXtpLAaz0Rl.jpg",
    slug: "movie/348350-solo-a-star-wars-story",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 1966,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 743,
      top: 280.5,
      width: 34,
      isMini: true,
    },
  },
  {
    id: "tv-92830-obi-wan-kenobi",
    title: "Obi-Wan Kenobi",
    mediaType: "tv",
    mediaId: 92830,
    releaseYear: 2024,
    inUniverseTime: "9 BBY",
    customPosterPath: "/qJRB789ceLryrLvOKrZqLKr2CGf.jpg",
    slug: "tv/92830-obi-wan-kenobi",
    canon: "canon",
    markerType: "split",
    zoomedIn: {
      left: 2124,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 775,
      top: 280.5,
      width: 34,
      isMini: true,
    },
  },
  {
    id: "tv-60554-star-wars-rebels",
    title: "Star Wars Rebels",
    mediaType: "tv",
    mediaId: 60554,
    releaseYear: 2024,
    inUniverseTime: "5 BBY to 1 BBY, epilogue after Endor",
    customPosterPath: "/eLrScs6Bs26JMcS8hiZhf7YRROr.jpg",
    slug: "tv/60554-star-wars-rebels",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 2282,
      top: 392,
      width: 130,
    },
    zoomedOut: {
      left: 807,
      top: 492.5,
      width: 34,
      isMini: true,
    },
  },
  {
    id: "tv-83867-andor",
    title: "Andor",
    mediaType: "tv",
    mediaId: 83867,
    releaseYear: 2024,
    inUniverseTime: "5 BBY to 1 BBY",
    customPosterPath: "/khZqmwHQicTYoS7Flreb9EddFZC.jpg",
    slug: "tv/83867-andor",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 2440,
      top: 392,
      width: 130,
    },
    zoomedOut: {
      left: 839,
      top: 492.5,
      width: 34,
      isMini: true,
    },
  },
  {
    id: "movie-330459-rogue-one-a-star-wars-story",
    title: "Rogue One: A Star Wars Story",
    mediaType: "movie",
    mediaId: 330459,
    releaseYear: 2024,
    inUniverseTime: "0 BBY, the days before A New Hope",
    customPosterPath: "/i0yw1mFbB7sNGHCs7EXZPzFkdA1.jpg",
    slug: "movie/330459-rogue-one-a-star-wars-story",
    canon: "canon",
    markerType: "merge",
    zoomedIn: {
      left: 2598,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 877,
      top: 246,
      width: 98,
      isMini: false,
    },
  },
  {
    id: "movie-11-star-wars",
    title: "Star Wars",
    mediaType: "movie",
    mediaId: 11,
    releaseYear: 2024,
    inUniverseTime: "0 BBY, the Battle of Yavin",
    customPosterPath: "/fai0rspsNeJCS69wHNjOdWxcI7P.jpg",
    slug: "movie/11-star-wars",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 2756,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 985,
      top: 246,
      width: 98,
      isMini: false,
    },
  },
  {
    id: "movie-1891-the-empire-strikes-back",
    title: "The Empire Strikes Back",
    mediaType: "movie",
    mediaId: 1891,
    releaseYear: 2024,
    inUniverseTime: "3 ABY",
    customPosterPath: "/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg",
    slug: "movie/1891-the-empire-strikes-back",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 2914,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 1093,
      top: 246,
      width: 98,
      isMini: false,
    },
  },
  {
    id: "movie-1892-return-of-the-jedi",
    title: "Return of the Jedi",
    mediaType: "movie",
    mediaId: 1892,
    releaseYear: 2024,
    inUniverseTime: "4 ABY",
    customPosterPath: "/jQYlydvHm3kUix1f8prMucrplhm.jpg",
    slug: "movie/1892-return-of-the-jedi",
    canon: "canon",
    markerType: "split",
    zoomedIn: {
      left: 3072,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 1201,
      top: 246,
      width: 98,
      isMini: false,
    },
  },
  {
    id: "tv-82856-the-mandalorian",
    title: "The Mandalorian",
    mediaType: "tv",
    mediaId: 82856,
    releaseYear: 2024,
    inUniverseTime: "9 ABY",
    customPosterPath: "/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg",
    slug: "tv/82856-the-mandalorian",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 3230,
      top: 392,
      width: 130,
    },
    zoomedOut: {
      left: 1309,
      top: 458,
      width: 98,
      isMini: false,
    },
  },
  {
    id: "tv-115036-the-book-of-boba-fett",
    title: "The Book of Boba Fett",
    mediaType: "tv",
    mediaId: 115036,
    releaseYear: 2024,
    inUniverseTime: "9 ABY",
    customPosterPath: "/gNbdjDi1HamTCrfvM9JeA94bNi2.jpg",
    slug: "tv/115036-the-book-of-boba-fett",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 3388,
      top: 392,
      width: 130,
    },
    zoomedOut: {
      left: 1411,
      top: 492.5,
      width: 34,
      isMini: true,
    },
  },
  {
    id: "tv-114461-ahsoka",
    title: "Ahsoka",
    mediaType: "tv",
    mediaId: 114461,
    releaseYear: 2024,
    inUniverseTime: "9 ABY",
    customPosterPath: "/eiJeWeCAEZAmRppnXHiTWDcCd3Q.jpg",
    slug: "tv/114461-ahsoka",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 3546,
      top: 392,
      width: 130,
    },
    zoomedOut: {
      left: 1443,
      top: 492.5,
      width: 34,
      isMini: true,
    },
  },
  {
    id: "tv-202879-star-wars-skeleton-crew",
    title: "Star Wars: Skeleton Crew",
    mediaType: "tv",
    mediaId: 202879,
    releaseYear: 2024,
    inUniverseTime: "About 9 ABY",
    customPosterPath: "/srQbJhLRKoAwRrNN5ga7webPHbC.jpg",
    slug: "tv/202879-star-wars-skeleton-crew",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 3704,
      top: 392,
      width: 130,
    },
    zoomedOut: {
      left: 1475,
      top: 492.5,
      width: 34,
      isMini: true,
    },
  },
  {
    id: "movie-1228710-the-mandalorian-and-grogu",
    title: "The Mandalorian and Grogu",
    mediaType: "movie",
    mediaId: 1228710,
    releaseYear: 2024,
    inUniverseTime: "11 ABY or later",
    customPosterPath: "/uwMKWjcNID0D9jjplsjkQS2OrB4.jpg",
    slug: "movie/1228710-the-mandalorian-and-grogu",
    canon: "canon",
    markerType: "merge",
    zoomedIn: {
      left: 3862,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 1513,
      top: 246,
      width: 98,
      isMini: false,
    },
  },
  {
    id: "tv-79093-star-wars-resistance",
    title: "Star Wars Resistance",
    mediaType: "tv",
    mediaId: 79093,
    releaseYear: 2024,
    inUniverseTime: "34 ABY to 35 ABY",
    customPosterPath: "/xul6SG8rar3wkHPY8YusUtxcdlZ.jpg",
    slug: "tv/79093-star-wars-resistance",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 4020,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 1615,
      top: 280.5,
      width: 34,
      isMini: true,
    },
  },
  {
    id: "movie-140607-star-wars-the-force-awakens",
    title: "Star Wars: The Force Awakens",
    mediaType: "movie",
    mediaId: 140607,
    releaseYear: 2024,
    inUniverseTime: "34 ABY",
    customPosterPath: "/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg",
    slug: "movie/140607-star-wars-the-force-awakens",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 4178,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 1653,
      top: 246,
      width: 98,
      isMini: false,
    },
  },
  {
    id: "movie-181808-star-wars-the-last-jedi",
    title: "Star Wars: The Last Jedi",
    mediaType: "movie",
    mediaId: 181808,
    releaseYear: 2024,
    inUniverseTime: "34 ABY, straight after The Force Awakens",
    customPosterPath: "/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg",
    slug: "movie/181808-star-wars-the-last-jedi",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 4336,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 1761,
      top: 246,
      width: 98,
      isMini: false,
    },
  },
  {
    id: "movie-181812-star-wars-the-rise-of-skywalker",
    title: "Star Wars: The Rise of Skywalker",
    mediaType: "movie",
    mediaId: 181812,
    releaseYear: 2024,
    inUniverseTime: "35 ABY",
    customPosterPath: "/db32LaOibwEliAmSL2jjDF6oDdj.jpg",
    slug: "movie/181812-star-wars-the-rise-of-skywalker",
    canon: "canon",
    markerType: "split",
    zoomedIn: {
      left: 4494,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 1869,
      top: 246,
      width: 98,
      isMini: false,
    },
  },
  {
    id: "movie-1417668-star-wars-starfighter",
    title: "Star Wars: Starfighter",
    mediaType: "movie",
    mediaId: 1417668,
    releaseYear: 2024,
    inUniverseTime: "May 28, 2027",
    customPosterPath: "/6LJetiEQjXUE9kDpXavXpZN1Vjk.jpg",
    slug: "movie/1417668-star-wars-starfighter",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 4652,
      top: 216,
      width: 130,
    },
    zoomedOut: {
      left: 1971,
      top: 280.5,
      width: 34,
      isMini: true,
    },
  },
  {
    id: "tv-114478-star-wars-visions",
    title: "Star Wars: Visions",
    mediaType: "tv",
    mediaId: 114478,
    releaseYear: 2024,
    inUniverseTime: "Outside the canon, undated",
    customPosterPath: "/lG9ltUP4FwvsQBcwOJYceDbP48E.jpg",
    slug: "tv/114478-star-wars-visions",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 4810,
      top: 40,
      width: 130,
    },
    zoomedOut: {
      left: 2003,
      top: 68.5,
      width: 34,
      isMini: true,
    },
  },
  {
    id: "tv-289324-star-wars-visions-presents-the-ninth-jedi",
    title: "Star Wars: Visions Presents - The Ninth Jedi",
    mediaType: "tv",
    mediaId: 289324,
    releaseYear: 2024,
    inUniverseTime: "About 234 ABY, its own far future",
    customPosterPath: "/AthqHRKJFOIbLa459I3D5yHdrQL.jpg",
    slug: "tv/289324-star-wars-visions-presents-the-ninth-jedi",
    canon: "canon",
    markerType: null,
    zoomedIn: {
      left: 4968,
      top: 40,
      width: 130,
    },
    zoomedOut: {
      left: 2035,
      top: 68.5,
      width: 34,
      isMini: true,
    },
  },
  // Legends Titles (when Legends switch is ON)
  {
    id: "tv-3122-star-wars-clone-wars",
    title: "Star Wars: Clone Wars",
    mediaType: "tv",
    mediaId: 3122,
    releaseYear: 2003,
    inUniverseTime: "22 to 19 BBY (Legends)",
    customPosterPath: "/jKfAVTGkf9qpGPZ4E1pNKdW6vra.jpg",
    slug: "tv/3122-star-wars-clone-wars",
    canon: "legends",
    markerType: null,
    zoomedIn: { left: 860, top: 480, width: 130 },
    zoomedOut: { left: 373, top: 492.5, width: 34, isMini: true },
  },
  {
    id: "movie-74849-the-star-wars-holiday-special",
    title: "The Star Wars Holiday Special",
    mediaType: "movie",
    mediaId: 74849,
    releaseYear: 1978,
    inUniverseTime: "1 ABY (Legends)",
    customPosterPath: "/lGJDx7RCgyMMa3owtp150umMnnJ.jpg",
    slug: "movie/74849-the-star-wars-holiday-special",
    canon: "legends",
    markerType: null,
    zoomedIn: { left: 2600, top: 480, width: 130 },
    zoomedOut: { left: 1040, top: 492.5, width: 34, isMini: true },
  },
  {
    id: "movie-1884-the-ewok-adventure",
    title: "The Ewok Adventure",
    mediaType: "movie",
    mediaId: 1884,
    releaseYear: 1984,
    inUniverseTime: "3 ABY (Legends)",
    customPosterPath: "/4GrECLKaJhYA6ooSTOG0XEuPnSl.jpg",
    slug: "movie/1884-the-ewok-adventure",
    canon: "legends",
    markerType: null,
    zoomedIn: { left: 3000, top: 480, width: 130 },
    zoomedOut: { left: 1180, top: 492.5, width: 34, isMini: true },
  },
  {
    id: "movie-10372-ewoks-the-battle-for-endor",
    title: "Ewoks: The Battle for Endor",
    mediaType: "movie",
    mediaId: 10372,
    releaseYear: 1985,
    inUniverseTime: "3 ABY (Legends)",
    customPosterPath: "/ntgKdekb7xMKscyh2Hei706LBLf.jpg",
    slug: "movie/10372-ewoks-the-battle-for-endor",
    canon: "legends",
    markerType: null,
    zoomedIn: { left: 3150, top: 480, width: 130 },
    zoomedOut: { left: 1220, top: 492.5, width: 34, isMini: true },
  },
  {
    id: "tv-25-star-wars-droids",
    title: "Star Wars: Droids",
    mediaType: "tv",
    mediaId: 25,
    releaseYear: 1985,
    inUniverseTime: "15 BBY (Legends)",
    customPosterPath: "/AuGZbGeOQt30zsoTUSPlS8kMe1v.jpg",
    slug: "tv/25-star-wars-droids",
    canon: "legends",
    markerType: null,
    zoomedIn: { left: 3300, top: 480, width: 130 },
    zoomedOut: { left: 1260, top: 492.5, width: 34, isMini: true },
  },
  {
    id: "tv-3478-ewoks",
    title: "Ewoks",
    mediaType: "tv",
    mediaId: 3478,
    releaseYear: 1985,
    inUniverseTime: "3 ABY (Legends)",
    customPosterPath: "/gu7FdhTki8lBiGceQlsL7H6o3ky.jpg",
    slug: "tv/3478-ewoks",
    canon: "legends",
    markerType: null,
    zoomedIn: { left: 3450, top: 480, width: 130 },
    zoomedOut: { left: 1300, top: 492.5, width: 34, isMini: true },
  },
];
